spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: liquibase/changelog.xml

server:
  port: 8081